### ISSUE TITLE
Problems when building from scratch/Dockerfile

### ISSUE THREAD

**Issue by jason-fox** [Engineering-Research-and-Development/opc-ua-car-server#9]
From the existing repo running the following:

```console
npm install
node car.js
```

```text

AssertionError [ERR_ASSERTION]: fs.existsSync(this.certificateFile), "Certificate file must exist :" + this.certificateFile
    at new AssertionError (internal/assert.js:269:11)
    at assert (/Users/jasonfox/Workspace/jason-fox/catalogue-forks/opc-ua-car-server/node_modules/better-assert/index.js:32:13)
    at OPCUAServer.OPCUASecureObject.getCertificateChain (/Users/jasonfox/Workspace/jason-fox/catalogue-forks/opc-ua-car-server/node_modules/node-opcua/lib/misc/opcua_secure_object.js:61:9)
    at new OPCUAServer (/Users/jasonfox/Workspace/jason-fox/catalogue-forks/opc-ua-car-server/node_modules/node-opcua/lib/server/opcua_server.js:251:32)
    at Object.<anonymous> (/Users/jasonfox/Workspace/jason-fox/catalogue-forks/opc-ua-car-server/car.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

where do I get the certificates?

From the proposed [Dockerfile](https://github.com/Engineering-Research-and-Development/opc-ua-car-server/pull/8) - if running as any user except `ROOT`, e.g. `USER Node` - I get the following:

```text

Error: EACCES: permission denied, open '/opt/opc-ua-car/node_modules/node-opcua/_generated_/_auto_generated_SubscriptionDiagnostics.js'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at LineFile.save (/opt/opc-ua-car/node_modules/node-opcua/lib/misc/linefile.js:19:8)
    at produce_code (/opt/opc-ua-car/node_modules/node-opcua/lib/misc/factory_code_generator.js:628:11)
    at registerObject (/opt/opc-ua-car/node_modules/node-opcua/lib/misc/factories.js:118:20)
    at Object.<anonymous> (/opt/opc-ua-car/node_modules/node-opcua/schemas/39394884f696ff0bf66bacc9a8032cc074e0158e/SubscriptionDiagnostics.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

Leaving the dockerization as `ROOT` is insecure.

**Comment by gabrieledeluca** [comment]
Thanks @jason-fox we fixed the error on both versions
